# Generated by Django 3.2.5 on 2021-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('mobile', models.IntegerField(default='', max_length=10)),
                ('image', models.ImageField(default='', upload_to='upload')),
            ],
        ),
    ]
