# Generated by Django 3.2.5 on 2021-07-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_colleges_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colleges',
            new_name='college',
        ),
    ]
