# Generated by Django 3.2.5 on 2021-08-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendance',
            new_name='student',
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('attid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('intime', models.DateTimeField(auto_now_add=True)),
                ('outtime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student')),
            ],
        ),
    ]
