# Generated by Django 3.2.5 on 2021-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20210802_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='rollno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
