# Generated by Django 3.2.5 on 2021-08-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_attendence_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='userid',
            new_name='id',
        ),
    ]
